######### This code contains WEPP data related information #########
## Author: stat_cat
## Date: 02/04/19



# STRIPS-1 Configurations -------------------------------------------------
library("devtools")
library(dplyr)
install_github("ISU-STRIPS/STRIPS")
STRIPSMeta::watersheds -> watersheds

# comments: have information on the name and slope of watershed
watersheds %>%  mode() #list
watersheds




# WEPP - climate input - real data -----------------------------------------
## these input file have been automatically generated by the WEPP model.
# It has the same parameters as the real climate file: the same station,
# the same coordinates. Year is not given, since it is not real.

climate_wepp <- read.table("data/climate/092.63x040.90.cli.txt",
                           skip = 15,
                           header = FALSE,
                           sep = "\t")
head(climate_wepp)
dim(climate_wepp)
climate_wepp <- as.data.frame(matrix(climate_wepp$V1, byrow = TRUE, ncol = 14))
colnames(climate_wepp) <- c("day",  "month", "year", "prcp", "dur",
                            "tp", "ip", "tmax", "tmin", "rad", "w-vl",
                            "w-dir", "tdew")
climate_wepp %>% head()
dim(climate_wepp)

# how many years simulated:
climate_wepp$year %>% unique() #100 years -- good





# WEPP - distance sediment loss -------------------------------------------
## read in dsl data -- write a function




# WEPP - soil loss  --------------------------------------------------------
## write here a function which takes in all of them!!!



# function to read in
library(dplyr)
get_env_results <- function() {
### write documentation here ###
    # declare names of watersheds
    watersheds <- c("bw1", "bw2", "bw3", "bw4", "bw5", "bw6",
                    "int1", "int2", "int3", "orb1", "orb2", "orb3")
    
    # declare hills
    hills <- c("h1", "h2", "h3", "h4")
    
    # dataset frame
    df <- data.frame(day = NA, mo = NA, year = NA, Precp = NA, Runoff = NA,
                     IR.det = NA, Av.det = NA, Mx.det = NA, Point = NA, 
                     Av.dep = NA, Max.dep = NA, Point.1 = NA, Sed.Del = NA,
                     ER = NA, HUC_12 = NA, field = NA, hill = NA)
    
    # for faster and correct reading of tables
    col_types <- c("integer", "integer", "integer", "numeric", "numeric", "numeric",
                   "numeric", "numeric", "numeric","numeric", "numeric",
                   "numeric", "numeric", "numeric")
    
    # column names
    col_names <- c("day", "mo", "year", "Precp", "Runoff", "IR.det",
                   "Av.det", "Mx.det", "Point", "Av.dep", "Max.dep",
                   "Point.1","Sed.Del", "ER")
    
    for (i in 1:12) {
        # check if interim 1
        if (i == 8) {
            for (j in 1:4) {
                path <- paste("data/env_results/071000081505_",
                              watersheds[i], "_", hills[j],
                              ".env", sep = "")
                data <- read.table(path, skip = 3, header = FALSE,
                                   col.names = col_names,
                                   colClasses = col_types)
                data <- data %>% mutate(HUC_12 = 071000081505,
                                             field = watersheds[i],
                                             hill = j)
                # add to the main dataset
                df <- rbind(df, data)
                
            }
        # check if interim 3
        } else if (i == 9) {
            for (j in 1:2) {
                path <- paste("data/env_results/071000081505_",
                              watersheds[i], "_", hills[j],
                              ".env", sep = "")
                data <- read.table(path, skip = 3, header = FALSE,
                                   col.names = col_names,
                                   colClasses = col_types)
                data <- data %>% mutate(HUC_12 = 071000081505,
                                             field = watersheds[i],
                                             hill = j)
                # add to the main dataset
                df <- rbind(df, data)
            }
        } else {
            for (j in 1:3) {
                path <- paste("data/env_results/071000081505_",
                              watersheds[i], "_", hills[j],
                              ".env", sep = "")
                data <- read.table(path, skip = 3, header = FALSE,
                                   col.names = col_names,
                                   colClasses = col_types)
                data <- data %>% mutate(HUC_12 = 071000081505,
                                             field = watersheds[i],
                                             hill = j)
                # add to the main dataset
                df <- rbind(df, data)
            }
        }
    }
    df <- df[-1,]
    return(df)
}

# get the whole dataset
soil_loss_all <- get_env_results()
soil_loss_all %>% glimpse()

### Replace yearSS!!!!!!
### convert charachters to numeric ones!!!!



# Collect data into one - Real --------------------------------------------
# convert Runoff to numeric
soil_loss_wepp$IR.det <- as.numeric(as.character(soil_loss_wepp$IR.det))

soil_loss_wepp %>% select(year, IR.det) %>% group_by(year) %>% 
    summarise(mean_soil_loss = sum(IR.det)) %>% unlist() %>% 
    matrix(ncol = 2, byrow = FALSE) %>% data.frame() -> sl_wepp

colnames(sl_wepp) <- c("year", "soil_loss")

# get precipitation
get_prcp <- function(df) {
    
    d <- data.frame(t(1:365))
    
    for (i in 1:12) {
        temp <- df[df[,1] == i,2]
        d <- rbind(d, temp)
    }
    
    d <- d[-1,]
    
    return(d)
}


# cbind all into one
wepp_data <- cbind(prcp_wepp, sl_wepp[,-1])

















