######### This code contains WEPP data related information #########
## Author: stat_cat
## Date: 02/04/19



# STRIPS-1 Configurations -------------------------------------------------
library("devtools")
library(dplyr)
install_github("ISU-STRIPS/STRIPS")
STRIPSMeta::watersheds -> watersheds

# comments: have information on the name and slope of watershed
watersheds %>%  mode() #list
watersheds



# DEP - soil loss  --------------------------------------------------------
# this is a data file  generated from DEP' server manipulations with WEPP

# read the soil data set
soil_loss <- read.table("data/071000090603_2.env",
                        skip = 1,
                        header = TRUE)

# get rid of units
soil_loss <- soil_loss[-1,]
soil_loss %>% head() 
soil_loss %>% glimpse()

# there is some misundestanding with years
soil_loss$year %>% table() #why 12??? should be from 07 - 18???

# month
soil_loss$mo %>% table() #not consistent 

## so which one is real soil loss? runoff? Do we need these? or should
## we take the average of runoff?




# DEP - climate input - real data ----------------------------------------
## how to generate more climate data? Bootstarpping???

# read the climate data set
climate <- read.table("data/092.63x040.90.cli.txt", 
                      skip = 14, 
                      header = TRUE,
                      sep = "\t")
## data is damaged??? 




# WEPP - climate input - simulated by Cligen ------------------------------
## these input file have been automatically generated by the WEPP model.
# It has the same parameters as the real climate file: the same station,
# the same coordinates. Year is not given, since it is not real.

climate_wepp <- read.table("data/092.63x040.90.cli.txt",
                           skip = 15,
                           header = FALSE)
colnames(climate_wepp) <- c("day",  "month", "year", "prcp", "dur",
                            "tp", "ip", "tmax", "tmin", "rad", "w-vl",
                            "w-dir", "tdew")
climate_wepp %>% head()
dim(climate_wepp)

# how many years simulated:
climate_wepp$year %>% unique() #100 years -- good



# WEPP - soil loss output - server ----------------------------------------
# by the same technique we read soil_loss data
soil_loss_wepp <- read.table("data/071000090603_2_wepp.env",
                             skip = 1,
                             header = TRUE)

soil_loss_wepp <- soil_loss_wepp[-1,]
soil_loss_wepp %>% head()

# see if we have soil loss for 100 years too
soil_loss_wepp$year %>% unique() # -- nope?? again 12? whyyy

# dimension #### CAUTION: number of years simulated can't be larger
# than 12!!!! that's the only reason
dim(soil_loss_wepp)





# Collect data into one - Real --------------------------------------------
# convert Runoff to numeric
soil_loss_wepp$IR.det <- as.numeric(as.character(soil_loss_wepp$IR.det))

soil_loss_wepp %>% select(year, IR.det) %>% group_by(year) %>% 
    summarise(mean_soil_loss = sum(IR.det)) %>% unlist() %>% 
    matrix(ncol = 2, byrow = FALSE) %>% data.frame() -> sl_wepp

colnames(sl_wepp) <- c("year", "soil_loss")

# get precipitation
get_prcp <- function(df) {
    
    d <- data.frame(t(1:365))
    
    for (i in 1:12) {
        temp <- df[df[,1] == i,2]
        d <- rbind(d, temp)
    }
    
    d <- d[-1,]
    
    return(d)
}


climate_wepp %>% select(year, prcp) %>% get_prcp() -> prcp_wepp


# cbind all into one
wepp_data <- cbind(prcp_wepp, sl_wepp[,-1])














